# This file contains the config for actionlint.
# See https://github.com/rhysd/actionlint/blob/main/docs/config.md
#
# Primarily, we use this config to define some large runners that are not registered in actionlint
self-hosted-runner:
  labels:
    - ubuntu-24.04-v64
    - blacksmith-2vcpu-ubuntu-2404
    - blacksmith-4vcpu-ubuntu-2404
    - blacksmith-8vcpu-ubuntu-2404
    - blacksmith-16vcpu-ubuntu-2404
    - blacksmith-32vcpu-ubuntu-2404
