name: Download Bedrock Binaries
description: Download Bedrock Binaries

runs:
  using: composite
  steps:
    - name: Download binaries
      uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.10.0
      with:
        key: bedrock-binaries-${{ github.sha }}
        # Fail on cache miss to avoid odd chmod errors as the only visible error if this part
        # of the workflow fails.
        fail-on-cache-miss: true
        path: |
          bedrock
          test/test
          test/clustertest/clustertest
          test/clustertest/testplugin/testplugin.so
          test/sample_data/lottoNumbers.json

    - name: Set permissions of the new binary files
      run: |
        sudo chmod +x bedrock test/test test/clustertest/clustertest
      shell: bash
