name: Set up mirror certificates
description: Set up mirror certificates

runs:
  using: composite
  steps:
    - name: Install 1Password CLI
      # v1
      uses: 1password/install-cli-action@143a85f84a90555d121cde2ff5872e393a47ab9f
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ env.OP_SERVICE_ACCOUNT_TOKEN }}

    - name: Update SSL Certificates from 1Password
      run: |
        op document get --output expensify.ca.crt expensify.ca.crt && sudo cp expensify.ca.crt /usr/local/share/ca-certificates/expensify.ca.crt
        sudo update-ca-certificates
      shell: bash
