name: Set up Keyed Cache
description: Set up Keyed Cache

runs:
  using: composite
  steps:
    - name: Get Date for cache keying
      id: get-date
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      shell: bash

    - name: Set up cache
      uses: actions/cache@v4.0.0
      with:
        path: ${{ env.CCACHE_BASEDIR }}
        key: "${{ runner.os }}-${{ env.SCRIPT_NAME }}-${{ steps.get-date.outputs.date }}"
        restore-keys: |
          ${{ runner.os }}-${{ env.SCRIPT_NAME }}-
